// Automatically generated by categories.java.a8annotation.ToStringAnnotationProcessor
package categories.java.a8annotation;
public class ToStrings {
    public static String toString(categories.java.a8annotation.rect.Rectangle obj) {
        StringBuilder result = new StringBuilder();
        result.append("categories.java.a8annotation.rect.Rectangle");
        result.append("[");
        result.append(toString(obj.getTopLeft()));
        result.append(",");
        result.append("width=");
        result.append(toString(obj.getWidth()));
        result.append(",");
        result.append("height=");
        result.append(toString(obj.getHeight()));
        result.append("]");
        return result.toString();
    }
    public static String toString(Object obj) {
        return java.util.Objects.toString(obj);
    }
}
